name: npm publish

on:
  push:
    branches:
      - release
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Setup node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm publish
      run: |
        npm ci
        npm run build
        rm -r ./.github
        rm -r ./.husky
        rm -r ./images
        rm -r ./node_modules
        rm -r ./src
        rm ./.eslintignore
        rm ./.eslintrc.js
        rm ./.gitignore
        rm -r ./API.md
        rm -r ./CHANGELOG.md
        rm -r ./jest.config.js
        rm -r ./nodemon.json
        rm -r ./package-lock.json
        rm -r ./TODO.md
        rm -r ./tsconfig.json
        rm -r ./TUTORIAL.md
        rm -r ./Updating\ NPM\ Version.md
        npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}
        npm publish
      env:
        CI: true
